name: io_card_engine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flame: ^1.21.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  image: ^4.3.0
  logger: ^2.4.0
  pdf: ^3.11.1
  pdfx: ^2.8.0
  printing: ^5.13.4
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
