name: io_card_engine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flame: ">=1.21.0 <2.0.0"
  flutter:
    sdk: flutter
  flutter_riverpod: ">=2.6.1 <3.0.0"
  riverpod_annotation: ">=2.6.1 <3.0.0"
  logger: ">=2.4.0 <3.0.0"
  cardengine:
    path: ./cardengine


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <6.0.0"
  riverpod_generator: ">=2.6.2 <3.0.0"
  build_runner: ">=2.4.13 <3.0.0"
  custom_lint: ">=0.7.0 <2.0.0"
  riverpod_lint: ">=2.6.2 <3.0.0"

flutter:
  uses-material-design: true
  assets: [] # TODO
