name: cardengine
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/iomatix/ioCardEngine/tree/main

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flame: ">=1.21.0 <2.0.0"
  image: ">=4.3.0 <5.0.0"
  logger: ">=2.4.0 <3.0.0"
  uuid: ">=4.5.1 <5.0.0"
  printing: ">=5.13.4 <6.0.0"
  

dev_dependencies:
  lints: ">=4.0.0 <5.0.0"
  test: ">=1.24.0 <2.0.0"

assets: [] # TODO
