name: card_engine
description: Card Engine made by ioMatix based on the foundations of flutter & flame.
version: 0.1.0
# repository: https://github.com/iomatix/ioCardEngine/tree/main

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flame: ">=1.21.0 <2.0.0"
  flame_riverpod: ">=5.1.0 <6.0.0"
  flutter_riverpod: ">=2.6.1 <3.0.0"
  image: ">=4.3.0 <5.0.0"
  logger: ">=2.4.0 <3.0.0"
  uuid: ">=4.5.1 <5.0.0"
  printing: ">=5.13.4 <6.0.0"
  path_provider: ">=2.1.5 <3.0.0"
  path_provider_platform_interface: ">=2.1.2 <3.0.0"
  mutex: ">=3.1.0 <4.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ">=4.0.0 <5.0.0"
  mockito: ^5.4.4
  test: ">=1.24.0 <2.0.0"

flutter: 
  assets:
      - assets/images/
